tests ok helloweb ok14

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -27,13 +27,24 @@ jobs:
         run: chrome --version
       - name: Set up ChromeDriver
         run: |
-          CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
-          && CHROMEDRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION` \
-          && wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip \
-          && unzip chromedriver_linux64.zip \
-          && rm chromedriver_linux64.zip \
-          && sudo mv chromedriver /usr/local/bin/ \
-          && sudo chmod +x /usr/local/bin/chromedriver          
+          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
+          echo "Detected Chrome version: $CHROME_VERSION"
+          
+          # Vérifier si une version de ChromeDriver existe pour cette version de Chrome
+          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
+          
+          if [ -z "$CHROMEDRIVER_VERSION" ]; then
+            echo "Error: Unable to fetch ChromeDriver version for Chrome $CHROME_VERSION"
+            exit 1
+          fi
+          
+          echo "Detected ChromeDriver version: $CHROMEDRIVER_VERSION"
+          
+          wget -q https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
+          unzip chromedriver_linux64.zip
+          rm chromedriver_linux64.zip
+          sudo mv chromedriver /usr/local/bin/
+          sudo chmod +x /usr/local/bin/chromedriver         
       - name: Set up JDK 21
         uses: actions/setup-java@v4
         with:
